package edu.ifrs;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;

public class RodandooformulrioTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void rodandooformulrio() {
		driver.get("http://campusdigital.poa.ifrs.edu.br:8080/public/login/index.xhtml?windowId=7f7");
		driver.manage().window().setSize(new Dimension(800, 576));
		driver.findElement(By.id("authentication:username")).sendKeys("0760170");
		driver.findElement(By.id("authentication:password")).sendKeys("franktom");
		driver.findElement(By.id("authentication:password")).sendKeys(Keys.ENTER);
		driver.findElement(By.cssSelector(".ui-state-hover > .ui-menuitem-text")).click();
		driver.findElement(By.cssSelector(".ui-state-hover > .ui-menuitem-text")).click();
		driver.findElement(By.cssSelector("a > .bright_blue")).click();
	}
}
